feat(trivy): replace Azure container scan with trivy
StatCan/aaw-kubeflow-containers pull request #382
Opened 2022-08-17 18:35 UTC by Souheil-Yazji

# Description

Replaces Azure Container Scan with trivy. Note that dockle wasn't being used in the Azure container scan (run-quality-checks: false)

# Tests / Quality Checks

## Code review

- [ ] Have you added the `auto-deploy` tag to your PR before your most recent push to this repo?  This causes CI to build the image and push to our ACR, letting reviewers access the built image without having to create it themselves
- [ ] Have you chosen a reviewer, attached them as a reviewer to this PR, and messaged them with the SHA-pinned image name for the final image to test on the **dev cluster** (e.g. `k8scc01covidacrdev.azurecr.io/jupyterlab-cpu:746d058e2f37e004da5ca483d121bfb9e0545f2b`)?

2022-09-01 21:36 UTC, brendangadd requested changes

2022-09-01 21:36 UTC, brendangadd commented on .github/workflows/build_push.yaml
> +    #     trivy-version: "0.29.1"
If we're leaving Azure container-scan, then this block won't be coming back; in which case, remove it.

2022-09-01 21:36 UTC, brendangadd commented on .github/workflows/build_push.yaml
> +      if: steps.notebook-name.outputs.NOTEBOOK_NAME != 'sas'
Why not scan the SAS image?

2022-09-01 21:36 UTC, brendangadd commented on .github/workflows/build_push.yaml
> +        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin latest
Checksum the binary before using it, and pin a version to make things reproducible (and not fail the checksum).

2022-09-02 13:06 UTC, Souheil-Yazji commented on .github/workflows/build_push.yaml
> +      if: steps.notebook-name.outputs.NOTEBOOK_NAME != 'sas'
2 critical CVEs are detected in the SAS image, but apparently they were mitigated at some point. I don't agree with the sas image going unscanned but I am limiting the scope of this ticket and leaving the prior decision of not scanning it in. We can address this in another small pr. 
https://github.com/StatCan/daaas-private/issues/11

2022-09-02 13:34 UTC, Souheil-Yazji commented on .github/workflows/build_push.yaml
> +        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin latest
The binary is checksum-ed via the install.sh script I'm pulling here. I guess we can checksum the install.sh since that's what we're pulling from remote? see `hash_sha256_verify()` in https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh

2022-09-02 23:51 UTC, brendangadd approved these changes

2022-09-02 23:52 UTC, merged