update(Dockerfile): XDG_DATA_HOME to /etc/share
StatCan/aaw-kubeflow-containers pull request #455
Opened 2023-02-28 19:11 UTC by bryanpaget

# Description

This is a fix for https://github.com/StatCan/daaas/issues/1535, where we needed to change the location of the user's VSCode extensions and settings to avoid data loss due to overwriting `/home/jovyan` whenever Kubeflow workspace volumes are mounted.

2023-03-02 21:41 UTC, bryanpaget commented
My initial attempt at fixing this bug has not panned out as expected. Perhaps I just didn't do the due diligence. 

The only change I made for this first attempt was adding:

`ENV XDG_DATA_HOME=/etc/share`

to the Ubuntu Desktop Dockerfile.

2023-03-06 20:50 UTC, bryanpaget commented
I have achieved something resembling success, setting the undocumented environmental variable `VSCODE_EXTENSIONS` has enabled the extensions to show up on first boot.

![image](https://user-images.githubusercontent.com/8212170/223227630-a00bb8c9-439e-476b-9397-f18fa6cf0d88.png)

Found here in the source code:

https://github.com/microsoft/vscode/blob/64f8dd4634af8349176bc9b1a2080c5cbf3e9e17/src/vs/platform/environment/common/environmentService.ts#L142

2023-03-07 15:24 UTC, wg102 requested changes

2023-03-07 15:24 UTC, wg102 commented on docker-bits/0_cpu.Dockerfile
> +   fix-permissions /home/$NB_USER
Missing end of file newline

2023-03-07 15:24 UTC, wg102 commented on docker-bits/0_cpu_sas.Dockerfile
> +   fix-permissions /home/$NB_USER
Missing end of file newline

2023-03-07 15:24 UTC, wg102 commented on trigger.md
> +hello
...Why?

2023-03-07 15:47 UTC, Souheil-Yazji commented on trigger.md
> +hello
I think maybe he was trying to trigger the CI, should be removed.

2023-03-07 15:47 UTC, Souheil-Yazji commented on docker-bits/0_cpu.Dockerfile
> +   fix-permissions /home/$NB_USER
These already exist on master. Is the branch history up to date?

2023-03-07 16:31 UTC, Souheil-Yazji commented
![image](https://user-images.githubusercontent.com/35379392/223484738-bc999ed5-12d2-43e6-9b03-81e7a4835ea1.png)
Initial review of `remote-desktop:5c67a4f6` with default volume mount appears to load up the extensions successfully. It seems however that there's consistent crashing/dead loading of extenstions (they never load and process keeps spinning) from vscode. Investigating further.

2023-03-07 16:44 UTC, bryanpaget commented
> Initial review of `remote-desktop:5c67a4f6` with default volume mount appears to load up the extensions successfully. It seems however that there's consistent crashing/dead loading of extenstions (they never load and process keeps spinning) from vscode. Investigating further.
> 
> ![image](https://user-images.githubusercontent.com/35379392/223484738-bc999ed5-12d2-43e6-9b03-81e7a4835ea1.png)

I noticed this as well.

> 
> Additional observations from testing:
> 
> VSCODE takes a little while to load, and seems to have to "reinstall" or "reinitialize" the extensions. This could be due to there being two folders of interest: extensions and data. I'm thinking the data folder is still being wiped meaning some data pertaining to the extensions are not being kept and then it has to reinstall the extensions.
> Reusing volumes (previously created workspace and data volumes) works but the above issue persists where you have to wait a couple of minutes for the extensions to reinitialize.
> When you first boot up VSCODE you can see extension buttons on the sidebar, then they disappear, then they are slowly reinstalled.
> Aside from having to wait a minute for the extensions to load this seems to fix the issue.

https://github.com/StatCan/daaas/issues/1535#issuecomment-1457036213

2023-03-07 16:54 UTC, bryanpaget commented
> Getting @Jose-Matsuda to confirm behaviour as well. Feel free to test on your end @bryanpaget

I noticed this as well but it's a problem with the normal remote-desktop image in production as well. Not limited to this image.

2023-03-07 17:00 UTC, Jose-Matsuda commented
Yeah I'm getting it as well.
The below happens on an unclassified remote desktop 1,4,16.
![image](https://user-images.githubusercontent.com/23174198/223493719-e9352861-949f-4377-b53b-b2936a46d95a.png)

For the prob remote desktop same settings it hasnt given the above error but I do oddly only see two installed extensions
![image](https://user-images.githubusercontent.com/23174198/223494084-05ad81cc-022f-47ad-8ca8-6c0438c75430.png)

I'll take a look at the behaviour of the extensions without a volume attached on our current v1 remote desktop to see if we can get the 133 error

2023-03-07 17:07 UTC, bryanpaget commented
> Yeah I'm getting it as well. The below happens on an unclassified remote desktop 1,4,16. ![image](https://user-images.githubusercontent.com/23174198/223493719-e9352861-949f-4377-b53b-b2936a46d95a.png)
> 
> For the prob remote desktop same settings it hasnt given the above error but I do oddly only see two installed extensions ![image](https://user-images.githubusercontent.com/23174198/223494084-05ad81cc-022f-47ad-8ca8-6c0438c75430.png)
> 
> I'll take a look at the behaviour of the extensions without a volume attached on our current v1 remote desktop to see if we can get the 133 error

Here's the crash using the image in production, on dev, with a data volume attached. I tried to reproduce without a data volume but it didn't crash. Adding a data volume made it crash this time.

![image](https://user-images.githubusercontent.com/8212170/223496092-88144ae5-3dfa-416b-bd11-de59ac458948.png)

2023-03-07 17:12 UTC, bryanpaget commented
And here's the 133 on a regular production image on dev without a data volume:

![image](https://user-images.githubusercontent.com/8212170/223497113-b05c2375-c748-4a29-bb9e-e96005f118ba.png)

Proof:

![image](https://user-images.githubusercontent.com/8212170/223497163-48ae53aa-719d-4fc0-9f54-0332830974ef.png)

2023-03-07 17:36 UTC, wg102 approved these changes

2023-03-07 22:24 UTC, merged