novnc language bug
StatCan/aaw-kubeflow-containers pull request #470
Opened 2023-03-24 15:12 UTC by mathis-marcotte

# Description

fixes https://github.com/StatCan/daaas/issues/1525

# Tests / Quality Checks

## Are there breaking changes?
Ask yourself the next question;
- [ ] Do we want to maintain the previous image from which we had to do breaking changes from?

If no, then carry on. If yes, there is a breaking change and we **want to maintain the previous image** do the following
- [ ] Create a new branch for the current version (ex v1) based off the current master/main branch
- [ ]  Increment the tag in the CI for pushes to master/main (v1 to v2)
- [ ] Change the CI that on pushes to the newly created "v1" branch (the name of the newly created branch we want to maintain is) it will push to the ACR. 
## Automated Testing/build and deployment
- [ ] Does the image pass CI successfully (build, pass vulnerability scan, and pass automated test suite)?
- [ ] If new features are added (new image, new binary, etc), have new automated tests been added to cover these?
- [ ] If new features are added that require in-cluster testing (e.g. a new feature that needs to interact with kubernetes), have you added the `auto-deploy` tag to the PR before pushing in order to build and push the image to ACR so you can test it in cluster as a custom image?

## JupyterLab extensions

- [ ] Are all extensions "enabled" (`jupyter labextension list` from inside the notebook)?

## VS Code tests

- [ ] Does VS Code open?
- [ ] Can you install extensions?

## Code review

- [ ] Have you added the `auto-deploy` tag to your PR before your most recent push to this repo?  This causes CI to build the image and push to our ACR, letting reviewers access the built image without having to create it themselves
- [ ] Have you chosen a reviewer, attached them as a reviewer to this PR, and messaged them with the SHA-pinned image name for the final image to test on the **dev cluster** (e.g. `k8scc01covidacrdev.azurecr.io/jupyterlab-cpu:746d058e2f37e004da5ca483d121bfb9e0545f2b`)?

2023-03-29 17:46 UTC, vexingly requested changes

2023-03-29 17:46 UTC, vexingly commented on docker-bits/6_remote-desktop.Dockerfile
> +ARG NO_VNC_SHA=89b0354c94ad0b0c88092ec7a08e28086d3ed572f13660bac28d5470faaae9c1
The patch https://gist.githubusercontent.com/sylus/cb01e59056780a2161186139b25818fb/raw/99ebd62a304c661d5612ad72ebc318f70d02741c/feat-notebook-Patch-noVNC-for-notebooks.patch is based on novnc files by line number, if those files have been changed from version 1.3 > 1.4, the patch will need to be updated, please confirm.

2023-03-29 18:00 UTC, mathis-marcotte commented on docker-bits/6_remote-desktop.Dockerfile
> +ARG NO_VNC_SHA=89b0354c94ad0b0c88092ec7a08e28086d3ed572f13660bac28d5470faaae9c1
I did not know that. But, I willjust close the PR. This was mainly just to test if bumping the version would fix the bug, but it did not as the bug is still present in the noVNC repo. But this is useful information to know if we do end up needing to update noVNC versions.

2023-03-30 12:45 UTC, mathis-marcotte commented
closing as not relevent anymore

2023-03-30 12:45 UTC, closed without merging