Update base image to 22.04
StatCan/aaw-kubeflow-containers pull request #498
Opened 2023-08-09 17:42 UTC by bryanpaget

This is the commit to properly close: https://github.com/StatCan/aaw/issues/1784 with pull request: https://github.com/StatCan/aaw-kubeflow-containers/pull/492 (already reviewed up to this point by @vexingly.

2023-08-15 18:59 UTC, bryanpaget commented
The updated 22.04 images build and run locally but I'm having difficulties with the Github Actions runner.

2023-08-22 20:06 UTC, bryanpaget commented
RStudio does not launch. ![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/8212170/e0c8e019-e680-4e4d-a793-c89474c23527)

2023-08-22 20:11 UTC, bryanpaget commented
I may have installed incompatible versions of rstudio and rstudio-server.
![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/8212170/da4c43de-ef90-48cf-af58-c5884586d030)

2023-08-22 21:08 UTC, bryanpaget commented
> RStudio does not launch. ![image](https://user-images.githubusercontent.com/8212170/262470450-e0c8e019-e680-4e4d-a793-c89474c23527.png)

Updating the `rstudio.desktop` file to point to `/usr/bin/rstudio` fixes this issue.

2023-08-22 21:08 UTC, bryanpaget commented
> I may have installed incompatible versions of rstudio and rstudio-server. ![image](https://user-images.githubusercontent.com/8212170/262471440-da4c43de-ef90-48cf-af58-c5884586d030.png)

I found a slightly newer version of `rstudio-server` which matches `rstudio`'s version.

2023-08-23 12:29 UTC, bryanpaget commented
I've fixed the above two issues, but there is still one issue:

A "null" error upon opening rstudio-desktop:
![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/8212170/b920ae0a-b7f1-4d45-b625-00c262bcbda3)

2023-08-23 12:38 UTC, bryanpaget commented
R seems to function correctly and it's even running R 4.3.1! But I can't install any packages:

![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/8212170/d6f9fb2f-e543-4782-ae2c-ffb65dabeb38)

2023-08-25 14:32 UTC, bryanpaget commented
## Testing:

- JupyterLab CPU
- JupyterLab PyTorch
  - Unable to import torch. This problem exists on prod so it's not newly introduced. A ticket has been made to track the issue.
  - [ ] https://github.com/StatCan/aaw-kubeflow-containers/issues/514
- JupyterLab Tensorflow
- SAS
- RStudio
- Remote Desktop

2023-08-30 15:06 UTC, bryanpaget commented
- Still getting "null" error when opening rstudio-desktop on remote-desktop but it doesn't seem to cause any problems.

- There are some large files with names corresponding to rstudio-desktop and rstudio-server version numbers:
- 
![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/8212170/968dfd34-63f4-4b86-81d1-90b8d9d49033)

2023-09-05 22:18 UTC, bryanpaget commented
I have decided to post-pone the upgrade of the remote-desktop image. I have another PR for the downgrade:

- https://github.com/StatCan/aaw-kubeflow-containers/pull/519

2023-09-11 16:59 UTC, bryanpaget commented on .github/workflows/build_push.yaml
This has all been done upstream, it's included here because I rebased?

2023-09-11 17:01 UTC, bryanpaget commented on docker-bits/0_Rocker.Dockerfile
This is to update the base image for RStudio, the geospatial image can be investigated here:

- https://hub.docker.com/layers/rocker/geospatial/latest/images/sha256-c342802656060fde278b9f657b821d7faa34752226f0dc648d7a868466a04595?context=explore

2023-09-11 17:03 UTC, bryanpaget commented on docker-bits/0_cpu.Dockerfile
This is to update the base jupyterlab images (already out of date...):

- https://hub.docker.com/layers/jupyter/datascience-notebook/2023-08-07/images/sha256-f4782ec90d40ed8d9f64301bd95fb6a0e68e5f55e3abcd261233ba2853f76ea5?context=explore

2023-09-11 17:04 UTC, bryanpaget commented on docker-bits/0_cpu_sas.Dockerfile
The Jupyterlab cpu images are based on the same image as the SAS image. This change simply updates the SAS image to be the same as the jupyterlab cpu images:

- https://hub.docker.com/layers/jupyter/datascience-notebook/2023-08-07/images/sha256-f4782ec90d40ed8d9f64301bd95fb6a0e68e5f55e3abcd261233ba2853f76ea5?context=explore

2023-09-11 17:09 UTC, bryanpaget commented on docker-bits/1_CUDA-11.8.0.Dockerfile
I just added the `ENV OS_VER ubuntu2204` to the Dockerfile to help with future upgrades (using variables instead of hard-coded URLs).

2023-09-11 17:10 UTC, bryanpaget commented on docker-bits/1_CUDA-12.0.1.Dockerfile
I just added the `ENV OS_VER ubuntu2204` to the Dockerfile to help with future upgrades (using variables instead of hard-coded URLs).

2023-09-11 17:11 UTC, bryanpaget commented on docker-bits/6_jupyterlab.Dockerfile
1. Upgraded VSCODE and its extensions.
2. The pip and mamba installs are broken up since together they caused the Github Action to fail. Cleaning this up will be part of the Dockerfile redesign: https://gist.github.com/bryanpaget/abdd53466d875509f8280b83d0bd6e0c

2023-09-11 17:14 UTC, bryanpaget commented on docker-bits/6_remote-desktop.Dockerfile
Some packages changed from Ubuntu 20.04 to 22.04:

- `gvfs-bin` to `gvfs`
- `zlibc` to `xlib1g` and `zlibg-dev`
- `pspp` can just be installed using `apt`

2023-09-11 17:15 UTC, bryanpaget commented on docker-bits/6_remote-desktop.Dockerfile
The `websockify` work-around is no longer needed.

2023-09-11 17:15 UTC, bryanpaget commented on docker-bits/6_remote-desktop.Dockerfile
`RUN rm /usr/share/applications/exo-mail-reader.desktop` was causing build errors, so I removed the line. The `exo-mail-reader.desktop` is no longer in Ubuntu 22.04.

2023-09-11 17:16 UTC, bryanpaget commented on docker-bits/6_rstudio-server.Dockerfile
I broke `rstudio-server` out into its own file because we were intalling it on top of already installed `rstudio-server` in the Rocker based image, so I moved it out so we can include it in the images that need it and not the ones that already have it.

2023-09-11 17:21 UTC, bryanpaget commented on docker-bits/6_jupyterlab.Dockerfile
Lines 108 to 115 have the conda cleaning, permissions fixing mantra repeated twice.

```
conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER  \
    && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER
```

So I deleted the extra one.

2023-09-11 17:22 UTC, bryanpaget commented on docker-bits/6_rstudio.Dockerfile
We don't need to install rstudio-server this way.

2023-09-11 17:32 UTC, bryanpaget commented on docker-bits/∞_CMD_remote-desktop.Dockerfile
I moved the removal area to the end of the dockerfile for some reason.

2023-09-11 18:47 UTC, Jose-Matsuda requested changes
The SAS seemingly missing the `6_rstudio-server` in its Dockerfile is the only major thing I think, though I haven't tested this on dev just yet (though we may need another push if the automatic cleaner got to these images since the last push was over 2 weeks ago

2023-09-11 18:47 UTC, Jose-Matsuda commented on docker-bits/6_jupyterlab.Dockerfile
> +RUN pip3 --no-cache-dir install --quiet \
Just leaving a comment to say that we all acknowledge that refactoring dockerfiles is on the horizon and we shouldn't have all these `RUN`s just like this

2023-09-11 18:47 UTC, Jose-Matsuda commented on docker-bits/6_remote-desktop.Dockerfile
Can you say why the websockify work-around is no longer needed? I trust you it's so that we have a history of why certain things were removed n all

2023-09-11 18:47 UTC, Jose-Matsuda commented on docker-bits/6_rstudio.Dockerfile
yup with advent of `rstudio-server` 👍🏼

2023-09-12 14:36 UTC, bryanpaget commented
Some build errors for the VSCode extensions.

```Installing extensions...
Extension 'ms-python.python@2023.15.12411005' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: ms-python.python
Installing extensions...
Installing extension 'reditorsupport.r' v2.8.1...
Extension 'reditorsupport.r' v2.8.1 was successfully installed.
Installing extensions...
Extension 'ms-ceintl.vscode-language-pack-fr@1.82.2023082309' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: ms-ceintl.vscode-language-pack-fr```

2023-09-12 14:52 UTC, bryanpaget commented on docker-bits/0_Rocker.Dockerfile
Sure thing, that makes sense.

2023-09-12 14:57 UTC, bryanpaget commented on docker-bits/6_remote-desktop.Dockerfile
I mentioned this issue in the following ticket:
![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/8212170/712ebb56-e494-41e1-b2e9-a2f9275ce4a2)

https://github.com/StatCan/aaw/issues/1784#issuecomment-1652404401

2023-09-12 15:08 UTC, bryanpaget commented on docker-bits/6_rstudio-server.Dockerfile
Thank you, I was wrong to remove that.

2023-09-12 20:16 UTC, bryanpaget commented on docker-bits/6_rstudio-server.Dockerfile
I re-added rstudio-server to the SAS image, tested it and it works.

2023-09-12 20:20 UTC, bryanpaget commented
> Some build errors for the VSCode extensions.
> 
> ```
> Extension 'ms-python.python@2023.15.12411005' not found.
> Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
> Failed Installing Extensions: ms-python.python
> Installing extensions...
> Installing extension 'reditorsupport.r' v2.8.1...
> Extension 'reditorsupport.r' v2.8.1 was successfully installed.
> Installing extensions...
> Extension 'ms-ceintl.vscode-language-pack-fr@1.82.2023082309' not found.
> Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
> Failed Installing Extensions: ms-ceintl.vscode-language-pack-fr```
> ```

I downgraded the VSCode extensions to what we had before the upgrade and made another ticket to update those packages: 

- https://github.com/StatCan/aaw-kubeflow-containers/issues/523

2023-09-18 18:19 UTC, bryanpaget commented on docker-bits/6_jupyterlab.Dockerfile
Revert VSCode because other people may be doing that already.

2023-09-18 18:21 UTC, bryanpaget commented on docker-bits/6_jupyterlab.Dockerfile
Try reverting: 

```
'r-languageserver==0.3.16' \
'python-lsp-server==1.7.4' \
```

2023-09-18 18:23 UTC, bryanpaget commented on docker-bits/∞_CMD_remote-desktop.Dockerfile
This was moved to the bottom of the remote-desktop Dockerfile because it stopped working and moving it here made it work again.

2023-09-18 18:24 UTC, bryanpaget commented on make_helpers/get_branch_name.sh
Revert

2023-09-18 18:26 UTC, bryanpaget commented on resources/remote-desktop/desktop-files/rstudio.desktop
revert

2023-09-18 18:49 UTC, bryanpaget commented on docker-bits/6_jupyterlab.Dockerfile
Done.

2023-09-18 18:49 UTC, bryanpaget commented on docker-bits/6_jupyterlab.Dockerfile
Done.

2023-09-19 19:50 UTC, bryanpaget commented
### Testing

#### JupyterLab CPU

![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/8212170/735a0f4c-bb7e-489f-b13a-f1c2f6889fda)

2023-09-21 13:37 UTC, bryanpaget commented
> ### Testing
> #### JupyterLab CPU
> JupyterLab CPU has an issue with some jupyter plugins, maybe I need to run jupyter lab build somewhere?
> 
> ![image](https://user-images.githubusercontent.com/8212170/269077800-735a0f4c-bb7e-489f-b13a-f1c2f6889fda.png)
> 
> This message also comes up.
> 
> ![image](https://user-images.githubusercontent.com/8212170/269082801-603d8e14-5837-4d19-a51e-eade273cf1ac.png)
> 
> The above errors don't seem to cause any problems with using the image.
> 
> #### RStudio
> RStudio works but still struggles with `tidymodels`.
> 
> ![image](https://user-images.githubusercontent.com/8212170/269078590-ebb00ab1-ca2a-42d1-a0aa-031b7543a901.png)
> 
> #### Remote Desktop
> Remote Desktop works as it should as far as I can tell.
> 
> ![image](https://user-images.githubusercontent.com/8212170/269080212-f3875c19-293a-47ff-9024-ae964fc40cf3.png)
> 
> #### SAS
> Everything seems to work.

The issues with JupyterLab have been resolved by cleaning up the JupyterLab extension installation code and calling jupyter lab build in the appropriate place.

2023-09-27 13:46 UTC, chuckbelisle approved these changes
lgtm

2023-09-27 13:49 UTC, merged