remove mc-tenant-wrapper.sh and references to it
StatCan/aaw-kubeflow-containers pull request #615
Opened 2024-04-23 17:53 UTC by bryanpaget

`mc-tenant-wrapper.sh` has been removed.

2024-05-02 17:42 UTC, bryanpaget commented
This builds, and I am able to test it on dev but I am not able to test it on The Zone.

2024-05-03 16:00 UTC, mathis-marcotte requested changes

2024-05-03 16:00 UTC, mathis-marcotte commented on tests/general/test_packages.py
> +    "pytables"
pytables is not a package

2024-05-03 16:51 UTC, mathis-marcotte requested changes

2024-05-03 16:51 UTC, mathis-marcotte commented on .github/workflows/build_push.yaml
> +        echo "IMAGE_VERSION=testing-mc-tenant-wrapper" >> "$GITHUB_ENV"
you shouldnt change this image version. Just the registry change should be fine. Your image will be tagged with both "dev" and the branch name later in the workflow

2024-05-03 17:52 UTC, bryanpaget commented
I tested this in The Zone, I created a simple file called data.csv with one row and three columns, I copied it to the bucket, deleted the original, copied the file from the bucket back to my home dir. Success.

```(base) jovyan@remove-mc-tenant-wrapper-0:~$ mc cp myBucketAlias/s3bucket/data.csv ./data.csv --insecure
...ud.statcan.ca/s3bucket/data.csv: 18 B / 18 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 111 B/s 0s(base) jovyan@remove-mc-tenant-wrapper-0:~$ ```

2024-05-03 18:01 UTC, bryanpaget commented on tests/general/test_packages.py
> +    "pytables"
the package is called pytables and because of the way this test was designed it will try to import pytables, hence the above mapping between package names and import names. I could remove tables from that ignore list. That's why pyyaml is there. pyyaml also suffers a similar fate of not being the import name.

2024-05-03 18:08 UTC, mathis-marcotte commented on tests/general/test_packages.py
> +    "pytables"
That is true, I was just basic my thoughts on this https://pypi.org/project/tables/, but i guess pytables is the "english" name for it. Not much harm in keeping it in this list them, especially if this is a temporary change until we really fix the issue.

2024-05-06 14:44 UTC, merged